### ISSUE TITLE
Failure to load data tables

### ISSUE THREAD

**Issue by michaelkulbacki** [UBOdin/mimir-ui#1]
When trying to load a data table it fails and here is the info from the terminal console...

**Comment by michaelkulbacki** [comment]
[error] - play.core.server.netty.PlayDefaultUpstreamHandler - Cannot invoke the action
java.sql.BatchUpdateException: batch entry 0: [SQLITE_ERROR] SQL error or missing database (no such table: ratings1RAW)
    at org.sqlite.jdbc3.JDBC3Statement.executeBatch(JDBC3Statement.java:210)
    at mimir.sql.JDBCBackend.update(JDBCBackend.scala:120)
    at mimir.util.LoadCSV$.populateTable(LoadCSV.scala:68)
    at mimir.util.LoadCSV$.handleLoadTable(LoadCSV.scala:21)
    at mimir.Database.loadTable(Database.scala:313)
    at mimir.Database.loadTable(Database.scala:328)
    at mimir.Database.loadTable(Database.scala:325)
    at controllers.Application$$anonfun$loadTable$1$$anonfun$apply$1.apply(Application.scala:318)
    at controllers.Application$$anonfun$loadTable$1$$anonfun$apply$1.apply(Application.scala:312)
    at scala.Option.map(Option.scala:145)
    at controllers.Application$$anonfun$loadTable$1.apply(Application.scala:312)
    at controllers.Application$$anonfun$loadTable$1.apply(Application.scala:307)
    at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:408)
    at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:407)
    at play.api.mvc.Action$.invokeBlock(Action.scala:533)
    at play.api.mvc.Action$.invokeBlock(Action.scala:530)
    at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:493)
    at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105)
    at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105)
    at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
    at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:104)
    at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:103)
    at scala.Option.map(Option.scala:145)
    at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:103)
    at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:96)
    at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:524)
    at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:524)
    at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:560)
    at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:560)
    at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:537)
    at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:537)
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
    at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[error] - application - 

! @717ead91i - Internal server error, for (POST) [/loadTable] ->

play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[BatchUpdateException: batch entry 0: [SQLITE_ERROR] SQL error or missing database (no such table: ratings1RAW)]]
    at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:254)
    at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:180)
    at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179)
    at play.api.DefaultGlobal$.onError(GlobalSettings.scala:212)
    at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94)
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:273)
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:269)
    at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344)
    at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343)
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
    at play.api.libs.iteratee.Execution$trampoline$.executeScheduled(Execution.scala:109)
    at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:71)
    at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
    at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
    at scala.concurrent.Promise$class.complete(Promise.scala:55)
    at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153)
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23)
    at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.sql.BatchUpdateException: batch entry 0: [SQLITE_ERROR] SQL error or missing database (no such table: ratings1RAW)
    at org.sqlite.jdbc3.JDBC3Statement.executeBatch(JDBC3Statement.java:210)
    at mimir.sql.JDBCBackend.update(JDBCBackend.scala:120)
    at mimir.util.LoadCSV$.populateTable(LoadCSV.scala:68)
    at mimir.util.LoadCSV$.handleLoadTable(LoadCSV.scala:21)
    at mimir.Database.loadTable(Database.scala:313)
    at mimir.Database.loadTable(Database.scala:328)
    at mimir.Database.loadTable(Database.scala:325)
    at controllers.Application$$anonfun$loadTable$1$$anonfun$apply$1.apply(Application.scala:318)
    at controllers.Application$$anonfun$loadTable$1$$anonfun$apply$1.apply(Application.scala:312)
    at scala.Option.map(Option.scala:145)
    at controllers.Application$$anonfun$loadTable$1.apply(Application.scala:312)
    at controllers.Application$$anonfun$loadTable$1.apply(Application.scala:307)
    at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:408)
    at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:407)
    at play.api.mvc.Action$.invokeBlock(Action.scala:533)
    at play.api.mvc.Action$.invokeBlock(Action.scala:530)
    at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:493)
    at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105)
    at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105)
    at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
    at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:104)
    at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:103)
    at scala.Option.map(Option.scala:145)
    at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:103)
    at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:96)
    at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:524)
    at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:524)
    at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:560)
    at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:560)
    at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:537)
    at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:537)
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
    ... 6 common frames omitted

**Comment by michaelkulbacki** [comment]
`[error] - play.core.server.netty.PlayDefaultUpstreamHandler - Cannot invoke the action
java.sql.BatchUpdateException: batch entry 0: [SQLITE_ERROR] SQL error or missing database (no such table: ratings1RAW)
	at org.sqlite.jdbc3.JDBC3Statement.executeBatch(JDBC3Statement.java:210)
	at mimir.sql.JDBCBackend.update(JDBCBackend.scala:120)
	at mimir.util.LoadCSV$.populateTable(LoadCSV.scala:68)
	at mimir.util.LoadCSV$.handleLoadTable(LoadCSV.scala:21)
	at mimir.Database.loadTable(Database.scala:313)
	at mimir.Database.loadTable(Database.scala:328)
	at mimir.Database.loadTable(Database.scala:325)
	at controllers.Application$$anonfun$loadTable$1$$anonfun$apply$1.apply(Application.scala:318)
	at controllers.Application$$anonfun$loadTable$1$$anonfun$apply$1.apply(Application.scala:312)
	at scala.Option.map(Option.scala:145)
	at controllers.Application$$anonfun$loadTable$1.apply(Application.scala:312)
	at controllers.Application$$anonfun$loadTable$1.apply(Application.scala:307)
	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:408)
	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:407)
	at play.api.mvc.Action$.invokeBlock(Action.scala:533)
	at play.api.mvc.Action$.invokeBlock(Action.scala:530)
	at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:493)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:104)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:103)
	at scala.Option.map(Option.scala:145)
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:103)
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:96)
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:524)
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:524)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:560)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:560)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:537)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:537)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[error] - application - 

! @717ead91i - Internal server error, for (POST) [/loadTable] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[BatchUpdateException: batch entry 0: [SQLITE_ERROR] SQL error or missing database (no such table: ratings1RAW)]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:254)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:180)
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179)
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:212)
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94)
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:273)
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:269)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at play.api.libs.iteratee.Execution$trampoline$.executeScheduled(Execution.scala:109)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:71)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at scala.concurrent.Promise$class.complete(Promise.scala:55)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.sql.BatchUpdateException: batch entry 0: [SQLITE_ERROR] SQL error or missing database (no such table: ratings1RAW)
	at org.sqlite.jdbc3.JDBC3Statement.executeBatch(JDBC3Statement.java:210)
	at mimir.sql.JDBCBackend.update(JDBCBackend.scala:120)
	at mimir.util.LoadCSV$.populateTable(LoadCSV.scala:68)
	at mimir.util.LoadCSV$.handleLoadTable(LoadCSV.scala:21)
	at mimir.Database.loadTable(Database.scala:313)
	at mimir.Database.loadTable(Database.scala:328)
	at mimir.Database.loadTable(Database.scala:325)
	at controllers.Application$$anonfun$loadTable$1$$anonfun$apply$1.apply(Application.scala:318)
	at controllers.Application$$anonfun$loadTable$1$$anonfun$apply$1.apply(Application.scala:312)
	at scala.Option.map(Option.scala:145)
	at controllers.Application$$anonfun$loadTable$1.apply(Application.scala:312)
	at controllers.Application$$anonfun$loadTable$1.apply(Application.scala:307)
	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:408)
	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:407)
	at play.api.mvc.Action$.invokeBlock(Action.scala:533)
	at play.api.mvc.Action$.invokeBlock(Action.scala:530)
	at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:493)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:104)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:103)
	at scala.Option.map(Option.scala:145)
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:103)
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:96)
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:524)
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:524)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:560)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:560)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:537)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:537)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	... 6 common frames omitted
`
